import React, { useState } from 'react';
import { api } from '../lib/api';

export default function Receipts({ config, setStatusMessage }) {
  const [receiptPath, setReceiptPath] = useState(null);
  const [receiptContent, setReceiptContent] = useState('');
  const [validationResult, setValidationResult] = useState(null);
  const [absorbResult, setAbsorbResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isValidated, setIsValidated] = useState(false);

  const handleSelectFile = async () => {
    const file = await api.selectReceiptFile();
    if (file) {
      setReceiptPath(file);
      setValidationResult(null);
      setAbsorbResult(null);
      setIsValidated(false);
      setLoading(true);
      const res = await api.readReceiptFile(file);
      setLoading(false);
      if (res.success) {
        setReceiptContent(res.content);
      } else {
        setReceiptContent(`Error reading file: ${res.error}`);
      }
    }
  };

  const handleValidate = async () => {
    if (!config?.cartridgeRoot || !receiptPath) return;
    
    setLoading(true);
    setValidationResult('Validating...');
    setStatusMessage('Validating receipt...');
    
    const res = await api.validateReceipt(config.cartridgeRoot, receiptPath);
    setLoading(false);
    
    if (res.ok) {
      setValidationResult(`Validation Output:\n${res.stdout}`);
      setIsValidated(true);
      setStatusMessage('Receipt validated.');
    } else {
      setValidationResult(`Validation Error:\n${res.stderr}`);
      setIsValidated(false);
      setStatusMessage('Receipt validation failed.');
    }
  };

  const handleAbsorb = async () => {
    if (!config?.cartridgeRoot || !receiptPath || !isValidated) return;
    
    if (!window.confirm("This will write proposed memory updates into your cartridge. Proceed?")) {
      return;
    }
    
    setLoading(true);
    setAbsorbResult('Absorbing...');
    setStatusMessage('Absorbing receipt...');
    
    const res = await api.absorbReceipt(config.cartridgeRoot, receiptPath);
    setLoading(false);
    
    if (res.ok) {
      setAbsorbResult(`Absorb Output:\n${res.stdout}`);
      setStatusMessage('Receipt absorbed successfully.');
      setIsValidated(false); // require re-validation if they want to do it again somehow
    } else {
      setAbsorbResult(`Absorb Error:\n${res.stderr}`);
      setStatusMessage('Receipt absorb failed.');
    }
  };

  const handleReject = () => {
    setReceiptPath(null);
    setReceiptContent('');
    setValidationResult(null);
    setAbsorbResult(null);
    setIsValidated(false);
  };

  return (
    <div className="p-6 h-full flex flex-col">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-semibold">Receipt Inbox</h1>
        <button 
          onClick={handleSelectFile}
          className="bg-vscode-buttonPrimary hover:bg-vscode-buttonHover text-white px-4 py-2 rounded shadow transition-colors font-semibold"
        >
          Select Receipt File
        </button>
      </div>

      <div className="bg-yellow-900/30 border border-yellow-700/50 p-4 rounded mb-6 flex items-start space-x-3">
        <div className="text-yellow-500 mt-0.5">⚠️</div>
        <div>
          <h3 className="text-sm font-bold text-yellow-500">Security Warning: Untrusted Output</h3>
          <p className="text-xs text-yellow-200/80 mt-1">
            MEMORY_RECEIPT.md files are generated by external LLMs. They are untrusted suggestions and should be verified before absorbing them into your memory cartridge. Auto-absorb is disabled by design.
          </p>
        </div>
      </div>

      {!receiptPath && (
        <div className="flex-1 flex items-center justify-center border-2 border-dashed border-vscode-border rounded text-gray-500">
          <p>No receipt selected. Click "Select Receipt File" to begin review.</p>
        </div>
      )}

      {receiptPath && (
        <div className="flex-1 flex gap-6 min-h-0">
          <div className="w-1/2 flex flex-col border border-vscode-border rounded bg-[#0d0d0d] overflow-hidden">
            <div className="bg-vscode-inputBg px-4 py-2 border-b border-vscode-border flex justify-between items-center">
              <span className="text-sm font-semibold text-gray-300 truncate" title={receiptPath}>
                {receiptPath.split(/[/\\]/).pop()}
              </span>
              <span className="text-xs text-gray-500">Preview</span>
            </div>
            <div className="flex-1 p-4 overflow-auto">
              <pre className="text-xs text-gray-300 whitespace-pre-wrap font-mono">
                {receiptContent}
              </pre>
            </div>
          </div>

          <div className="w-1/2 flex flex-col space-y-4 overflow-y-auto pr-2">
            <div className="bg-vscode-inputBg p-4 rounded border border-vscode-border">
              <h3 className="text-sm font-semibold text-gray-400 uppercase mb-4">Workflow</h3>
              
              <div className="space-y-4">
                <button
                  onClick={handleValidate}
                  disabled={loading}
                  className="w-full bg-vscode-buttonPrimary hover:bg-vscode-buttonHover disabled:opacity-50 text-white px-4 py-2 rounded shadow transition-colors font-semibold"
                >
                  {loading && !isValidated && !absorbResult ? 'Running Validation...' : '1. Validate Receipt'}
                </button>
                
                <button
                  onClick={handleAbsorb}
                  disabled={loading || !isValidated}
                  className="w-full bg-green-700 hover:bg-green-600 disabled:opacity-50 disabled:bg-gray-800 disabled:text-gray-500 text-white px-4 py-2 rounded shadow transition-colors font-semibold"
                >
                  2. Approve & Absorb
                </button>

                <button
                  onClick={handleReject}
                  className="w-full bg-transparent border border-red-900/50 hover:bg-red-900/30 text-red-400 px-4 py-2 rounded shadow transition-colors text-sm"
                >
                  Reject / Ignore locally
                </button>
              </div>
            </div>

            {(validationResult || absorbResult) && (
              <div className="flex-1 flex flex-col min-h-0">
                <h3 className="text-sm font-semibold text-gray-400 uppercase mb-2">Logs</h3>
                <div className="flex-1 bg-[#0d0d0d] p-4 rounded border border-vscode-border font-mono text-xs overflow-auto whitespace-pre-wrap">
                  {validationResult && (
                    <div className={isValidated ? "text-blue-400 mb-4" : "text-red-400 mb-4"}>
                      {validationResult}
                    </div>
                  )}
                  {absorbResult && (
                    <div className={absorbResult.includes('Error') ? "text-red-400" : "text-green-400"}>
                      {absorbResult}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
