import React, { useState } from 'react';
import { api } from '../lib/api';
import { FileDown, CheckCircle, XCircle, AlertTriangle, FileCode2, TerminalSquare } from 'lucide-react';

export default function Receipts({ config, setStatusMessage }) {
  const [receiptPath, setReceiptPath] = useState(null);
  const [receiptContent, setReceiptContent] = useState('');
  const [validationResult, setValidationResult] = useState(null);
  const [absorbResult, setAbsorbResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [isValidated, setIsValidated] = useState(false);

  const handleSelectFile = async () => {
    const file = await api.selectReceiptFile();
    if (file) {
      setReceiptPath(file);
      setValidationResult(null);
      setAbsorbResult(null);
      setIsValidated(false);
      setLoading(true);
      const res = await api.readReceiptFile(file);
      setLoading(false);
      if (res.success) {
        setReceiptContent(res.content);
      } else {
        setReceiptContent(`Error reading file: ${res.error}`);
      }
    }
  };

  const handleValidate = async () => {
    if (!config?.cartridgeRoot || !receiptPath) return;
    
    setLoading(true);
    setValidationResult('Validating...\n');
    setStatusMessage('Validating receipt...');
    
    const res = await api.validateReceipt(config.cartridgeRoot, receiptPath);
    setLoading(false);
    
    if (res.ok) {
      setValidationResult(`Validation Passed:\n${res.stdout}`);
      setIsValidated(true);
      setStatusMessage('Receipt validated.');
    } else {
      setValidationResult(`Validation Error:\n${res.stderr}`);
      setIsValidated(false);
      setStatusMessage('Receipt validation failed.');
    }
  };

  const handleAbsorb = async () => {
    if (!config?.cartridgeRoot || !receiptPath || !isValidated) return;
    
    if (!window.confirm("This will write proposed memory updates into your cartridge. Proceed?")) {
      return;
    }
    
    setLoading(true);
    setAbsorbResult('Absorbing...\n');
    setStatusMessage('Absorbing receipt...');
    
    const res = await api.absorbReceipt(config.cartridgeRoot, receiptPath);
    setLoading(false);
    
    if (res.ok) {
      setAbsorbResult(`Absorb Success:\n${res.stdout}`);
      setStatusMessage('Receipt absorbed successfully.');
      setIsValidated(false); // require re-validation if they want to do it again somehow
    } else {
      setAbsorbResult(`Absorb Error:\n${res.stderr}`);
      setStatusMessage('Receipt absorb failed.');
    }
  };

  const handleReject = () => {
    setReceiptPath(null);
    setReceiptContent('');
    setValidationResult(null);
    setAbsorbResult(null);
    setIsValidated(false);
  };

  return (
    <div className="bg-brand-panel p-6 rounded-2xl border border-brand-border shadow-sm flex flex-col mt-6">
      <div className="flex justify-between items-center mb-6">
        <div className="flex items-center gap-3">
          <FileDown className="text-brand-accent" size={20} />
          <h2 className="text-lg font-bold text-brand-text">Review & Absorb Receipt</h2>
        </div>
        <button 
          onClick={handleSelectFile}
          className="bg-brand-surface border border-brand-border hover:bg-brand-border text-brand-text px-4 py-2 rounded-xl transition-colors font-bold shadow-sm flex items-center gap-2 text-sm"
        >
          <FileCode2 size={16} /> Select MEMORY_RECEIPT.md
        </button>
      </div>

      <div className="bg-brand-warning/10 border border-brand-warning/30 p-4 rounded-xl mb-6 flex items-start gap-3">
        <AlertTriangle className="text-brand-warning mt-0.5" size={18} />
        <div>
          <h3 className="text-sm font-bold text-brand-warning">Security Warning: Untrusted Output</h3>
          <p className="text-xs font-medium text-brand-warning/80 mt-1">
            Receipts are generated by external LLMs. They are untrusted suggestions and must be verified by the service before absorption. Auto-absorb is disabled by design.
          </p>
        </div>
      </div>

      {!receiptPath && (
        <div className="flex-1 flex flex-col items-center justify-center border-2 border-dashed border-brand-border rounded-xl text-brand-muted py-12 bg-brand-surface/50">
          <FileDown size={32} className="mb-4 opacity-50" />
          <p className="font-semibold">No receipt selected</p>
          <p className="text-sm opacity-75 mt-1">Click the button above to load an LLM's response.</p>
        </div>
      )}

      {receiptPath && (
        <div className="flex-1 flex gap-6 min-h-[350px]">
          {/* File Preview */}
          <div className="w-1/2 flex flex-col border border-brand-border rounded-xl bg-brand-surface overflow-hidden shadow-inner">
            <div className="bg-brand-panel px-4 py-3 border-b border-brand-border flex justify-between items-center">
              <span className="text-sm font-bold text-brand-text truncate" title={receiptPath}>
                {receiptPath.split(/[/\\]/).pop()}
              </span>
              <span className="text-xs font-semibold text-brand-muted uppercase tracking-widest">Preview</span>
            </div>
            <div className="flex-1 p-4 overflow-auto bg-[#1C1917]">
              <pre className="text-xs text-brand-muted whitespace-pre-wrap font-mono leading-relaxed">
                {receiptContent}
              </pre>
            </div>
          </div>

          {/* Workflow Controls & Logs */}
          <div className="w-1/2 flex flex-col gap-6 overflow-y-auto">
            <div className="bg-brand-surface p-5 rounded-xl border border-brand-border">
              <h3 className="text-xs font-bold tracking-widest text-brand-muted uppercase mb-4 flex items-center gap-2">
                <CheckCircle size={14} /> Workflow Actions
              </h3>
              
              <div className="flex flex-col gap-3">
                <button
                  onClick={handleValidate}
                  disabled={loading}
                  className="w-full bg-brand-surface border border-brand-border hover:bg-brand-border disabled:opacity-50 text-brand-text px-4 py-3 rounded-xl shadow-sm transition-colors font-bold flex items-center justify-center gap-2"
                >
                  {loading && !isValidated && !absorbResult ? <RefreshCcw size={16} className="animate-spin text-brand-accent" /> : <CheckCircle size={16} className={isValidated ? "text-brand-success" : "text-brand-muted"} />}
                  1. Validate Structure
                </button>
                
                <button
                  onClick={handleAbsorb}
                  disabled={loading || !isValidated}
                  className="w-full bg-brand-success hover:bg-[#2F855A] disabled:opacity-50 disabled:bg-brand-surface disabled:border disabled:border-brand-border disabled:text-brand-muted text-white px-4 py-3 rounded-xl shadow-sm transition-colors font-bold flex items-center justify-center gap-2"
                >
                  <FileDown size={16} />
                  2. Approve & Absorb to Brain
                </button>

                <button
                  onClick={handleReject}
                  className="w-full mt-2 bg-transparent border border-brand-danger/30 hover:bg-brand-danger/10 text-brand-danger px-4 py-3 rounded-xl transition-colors font-bold text-sm flex items-center justify-center gap-2"
                >
                  <XCircle size={16} /> Discard Receipt
                </button>
              </div>
            </div>

            {(validationResult || absorbResult) && (
              <div className="flex-1 flex flex-col min-h-0">
                <h3 className="text-xs font-bold tracking-widest text-brand-muted uppercase mb-3 flex items-center gap-2">
                  <TerminalSquare size={14} /> Execution Logs
                </h3>
                <div className="flex-1 bg-[#1C1917] p-4 rounded-xl border border-[#2D1B14] font-mono text-xs overflow-auto whitespace-pre-wrap shadow-inner leading-relaxed">
                  {validationResult && (
                    <div className={isValidated ? "text-brand-success mb-4 font-bold" : "text-brand-danger mb-4 font-bold"}>
                      {validationResult}
                    </div>
                  )}
                  {absorbResult && (
                    <div className={absorbResult.includes('Error') ? "text-brand-danger font-bold" : "text-brand-success font-bold"}>
                      {absorbResult}
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
