const { contextBridge, ipcRenderer } = require('electron');

const e2eMode = process.env.LLM_KOSH_E2E_MODE || '';

const e2eBridge = e2eMode
  ? {
      selectCartridgeRoot: async () => 'C:\\e2e\\root',
      createCartridgeRoot: async () => ({ ok: true, folder: 'C:\\e2e\\root' }),
      getStatus: async () => ({ ok: true, stdout: 'E2E status ok' }),
      selectExecutable: async () => 'llm-kosh',
      readConfig: async () => (
        e2eMode === 'onboarding'
          ? {}
          : {
              cartridgeRoot: 'C:\\e2e\\root',
              executablePath: 'llm-kosh',
              cliMode: 'Auto',
              daemonMode: 'auto',
            }
      ),
      writeConfig: async (config) => config,
      readCartridgeConfig: async () => ({ schema: 'llm-kosh.v0', version: '1.0.0', retrieval_weights: {} }),
      writeCartridgeConfig: async (rootPath, config) => config,
      revealInFolder: () => {},
      selectOutputFolder: async () => 'C:\\e2e\\exports',
      generatePack: async () => ({ ok: true, outPath: 'C:\\e2e\\exports\\pack.zip', stdout: 'Pack created' }),
      validatePack: async () => ({ ok: true, stdout: 'Pack valid' }),
      selectReceiptFile: async () => 'C:\\e2e\\receipt.md',
      readReceiptFile: async () => ({ success: true, content: '# MEMORY_RECEIPT\n' }),
      validateReceipt: async () => ({ ok: true, stdout: 'Receipt valid' }),
      absorbReceipt: async () => ({ ok: true, stdout: 'Receipt absorbed' }),
      setLoginItem: async () => ({ ok: true }),
      getServiceStatus: async () => ({ ok: true, isLocalRunning: false, stdout: 'Service stopped' }),
      getDaemonStatus: async () => ({ ok: true, isLocalRunning: false, stdout: 'Daemon stopped' }),
      getLocalServiceDetails: async () => ({ running: false }),
      getLocalDaemonDetails: async () => ({ running: false }),
      serviceOnce: async () => ({ ok: true, stdout: 'Service ran once' }),
      daemonOnce: async () => ({ ok: true, stdout: 'Daemon ran once' }),
      startMcp: async () => ({ ok: true }),
      stopMcp: async () => ({ ok: true }),
      getMcpStatus: async () => ({
        running: false,
        pid: null,
        startTime: null,
        lastEvent: 'Idle',
        logs: [],
      }),
      onMcpStatusChanged: () => () => {},
      onMcpLog: () => () => {},
      startService: async () => ({ ok: true }),
      startDaemon: async () => ({ ok: true }),
      stopService: async () => ({ ok: true }),
      stopDaemon: async () => ({ ok: true }),
      onServiceLog: () => () => {},
      onDaemonLog: () => () => {},
      listWatchedFolders: async () => ({ success: true, folders: [] }),
      addWatchedFolder: async () => ({ success: true, folders: ['C:\\e2e\\watched'] }),
      removeWatchedFolder: async () => ({ success: true, folders: [] }),
      readDirectory: async () => ({ success: true, items: [] }),
      testCli: async () => (
        e2eMode === 'onboarding'
          ? { ok: false, executablePath: null, mode: 'Auto', stderr: 'llm-kosh CLI not detected for E2E', exitCode: -1 }
          : { ok: true, executablePath: 'llm-kosh', mode: 'Bundled', version: '2.1.1', stdout: 'llm-kosh 2.1.1', stderr: '', exitCode: 0 }
      ),
      getLogs: async () => ({ ok: true, logs: [], config: {}, daemonRunning: false }),
      runSmokeTest: async () => ([
        { ok: true, step: 'create-temp-root', stdout: 'C:\\e2e\\root' },
        { ok: true, step: 'init' },
        { ok: true, step: 'status' },
        { ok: true, step: 'safe-pack' },
        { ok: true, step: 'validate-pack' },
        { ok: true, step: 'validate-receipt' },
        { ok: true, step: 'absorb' },
        { ok: true, step: 'service' },
        { ok: true, step: 'daemon' },
      ]),
      runKoshCommand: async () => ({ ok: true, stdout: 'Mock query output' }),
      installKosh: async () => ({ ok: true, stderr: '' }),
      uninstallKosh: async () => ({ ok: true, stderr: '' }),
      closeQuickCapture: () => {},
    }
  : null;

const bridge = e2eBridge || window.llmKosh || {
  selectCartridgeRoot: async () => 'C:\\mock\\root',
  createCartridgeRoot: async () => ({ ok: true, folder: 'C:\\mock\\root' }),
  getStatus: async () => ({ ok: true, stdout: 'Mock status' }),
  selectExecutable: async () => 'C:\\mock\\llm-kosh',
  readConfig: async () => ({ cartridgeRoot: 'C:\\mock\\root' }),
  writeConfig: async (cfg) => cfg,
  readCartridgeConfig: async () => ({ schema: 'llm-kosh.v0', version: '1.0.0', retrieval_weights: {} }),
  writeCartridgeConfig: async (r, cfg) => cfg,
  revealInFolder: () => {},
  selectOutputFolder: async () => 'C:\\mock\\exports',
  generatePack: async () => ({ ok: true, outPath: 'C:\\mock\\exports\\pack.zip' }),
  validatePack: async () => ({ ok: true }),
  selectReceiptFile: async () => 'C:\\mock\\receipt.md',
  readReceiptFile: async () => ({ success: true, content: 'Mock receipt content' }),
  validateReceipt: async () => ({ ok: true }),
  absorbReceipt: async () => ({ ok: true }),
  setLoginItem: async () => ({ ok: true }),
  getServiceStatus: async () => ({ ok: true, isLocalRunning: false }),
  getDaemonStatus: async () => ({ ok: true, isLocalRunning: false }),
  getLocalServiceDetails: () => ({ running: false }),
  getLocalDaemonDetails: () => ({ running: false }),
  serviceOnce: async () => ({ ok: true }),
  daemonOnce: async () => ({ ok: true }),
  startMcp: async () => {},
  stopMcp: async () => {},
  getMcpStatus: async () => ({ running: false, logs: [] }),
  onMcpStatusChanged: () => () => {},
  onMcpLog: () => () => {},
  startService: async () => {},
  startDaemon: async () => {},
  stopService: async () => {},
  stopDaemon: async () => {},
  onServiceLog: () => () => {},
  onDaemonLog: () => () => {},
  listWatchedFolders: async () => ({ success: true, folders: [] }),
  addWatchedFolder: async () => {},
  removeWatchedFolder: async () => {},
  readDirectory: async () => [],
  testCli: async () => ({ ok: true }),
  getLogs: async () => [],
  runSmokeTest: async () => ({ ok: true }),
  runKoshCommand: async () => ({ ok: true, stdout: 'Mock query output' }),
  installKosh: async () => ({ ok: true }),
  uninstallKosh: async () => ({ ok: true }),
  closeQuickCapture: () => {},
};

contextBridge.exposeInMainWorld('llmKosh', bridge);
