const bridge = window.llmKosh || {
  selectCartridgeRoot: async () => 'C:\\mock\\root',
  createCartridgeRoot: async () => ({ ok: true, folder: 'C:\\mock\\root' }),
  getStatus: async () => ({ ok: true, stdout: 'Mock status' }),
  selectExecutable: async () => 'C:\\mock\\llm-kosh',
  readConfig: async () => ({ cartridgeRoot: 'C:\\mock\\root' }),
  writeConfig: async (cfg) => cfg,
  readCartridgeConfig: async () => ({ schema: 'llm-kosh.v0', version: '1.0.0', retrieval_weights: {} }),
  writeCartridgeConfig: async (r, cfg) => cfg,
  revealInFolder: () => {},
  selectOutputFolder: async () => 'C:\\mock\\exports',
  generatePack: async () => ({ ok: true, outPath: 'C:\\mock\\exports\\pack.zip' }),
  validatePack: async () => ({ ok: true }),
  selectReceiptFile: async () => 'C:\\mock\\receipt.md',
  readReceiptFile: async () => ({ success: true, content: 'Mock receipt content' }),
  validateReceipt: async () => ({ ok: true }),
  absorbReceipt: async () => ({ ok: true }),
  setLoginItem: async () => ({ ok: true }),
  getServiceStatus: async () => ({ ok: true, isLocalRunning: false }),
  getDaemonStatus: async () => ({ ok: true, isLocalRunning: false }),
  getLocalServiceDetails: () => ({ running: false }),
  getLocalDaemonDetails: () => ({ running: false }),
  serviceOnce: async () => ({ ok: true }),
  daemonOnce: async () => ({ ok: true }),
  startMcp: async () => {},
  stopMcp: async () => {},
  getMcpStatus: async () => ({ running: false, logs: [] }),
  onMcpStatusChanged: () => () => {},
  onMcpLog: () => () => {},
  startService: async () => {},
  startDaemon: async () => {},
  stopService: async () => {},
  stopDaemon: async () => {},
  onServiceLog: () => () => {},
  onDaemonLog: () => () => {},
  listWatchedFolders: async () => ({ success: true, folders: [] }),
  addWatchedFolder: async () => {},
  removeWatchedFolder: async () => {},
  readDirectory: async () => [],
  testCli: async () => ({ ok: true }),
  getLogs: async () => [],
  runSmokeTest: async () => ({ ok: true }),
  runKoshCommand: async () => ({ ok: true, stdout: 'Mock query output' }),
  installKosh: async () => ({ ok: true }),
  uninstallKosh: async () => ({ ok: true }),
  closeQuickCapture: () => {},
};

export const api = {
  ...bridge,
  getServiceStatus: async (rootPath) => bridge.getServiceStatus(rootPath),
  getDaemonStatus: async (rootPath) => bridge.getDaemonStatus(rootPath),
  getLocalServiceDetails: async () => bridge.getLocalServiceDetails(),
  getLocalDaemonDetails: async () => bridge.getLocalDaemonDetails(),
  serviceOnce: async (rootPath, mode) => bridge.serviceOnce(rootPath, mode),
  daemonOnce: async (rootPath, mode) => bridge.daemonOnce(rootPath, mode),
  startMcp: async (rootPath, options) => bridge.startMcp(rootPath, options),
  stopMcp: async () => bridge.stopMcp(),
  getMcpStatus: async () => bridge.getMcpStatus(),
  onMcpStatusChanged: (cb) => bridge.onMcpStatusChanged(cb),
  onMcpLog: (cb) => bridge.onMcpLog(cb),
  startService: async (rootPath, mode) => bridge.startService(rootPath, mode),
  testCli: async () => bridge.testCli(),
  closeQuickCapture: () => bridge.closeQuickCapture?.(),
  readDirectory: async (dirPath) => bridge.readDirectory(dirPath),
  stopService: async () => bridge.stopService(),
  onServiceLog: (cb) => bridge.onServiceLog(cb),
  onDaemonLog: (cb) => bridge.onDaemonLog(cb),
  installKosh: async () => bridge.installKosh(),
  uninstallKosh: async () => bridge.uninstallKosh(),
};
